export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_INPUT_WITH_HOOKS = 'UPDATE_INPUT_WITH_HOOKS';
export const FETCH_USER_ATTEMPT = 'FETCH_USER_ATTEMPT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';
